--<ScriptOptions statementTerminator=";"/>

CREATE TABLE BOOKS (
	BOOKID INT NOT NULL,
	AUTHOR VARCHAR(100),
	COVERPAGE VARCHAR(75),
	DESCRIPTION VARCHAR(2000),
	DISCOUNT FLOAT,
	EDITION VARCHAR(20),
	ISBN VARCHAR(75),
	PRICE DOUBLE,
	PUBDATE VARCHAR(255),
	PUBLISHER VARCHAR(30),
	TITLE VARCHAR(75),
	PRIMARY KEY (BOOKID)
);

CREATE TABLE ORDERDETAIL (
	ORDERID INT NOT NULL,
	BOOKID INT,
	DATE DATE,
	SHIPPINGID INT,
	STATUS INT,
	USERID INT,
	PRIMARY KEY (ORDERID)
);

CREATE TABLE Tag (
	Books_BOOKID INT,
	TAGS VARCHAR(15)
);

CREATE TABLE LOGIN (
	LOGINID INT NOT NULL,
	PASSWORD VARCHAR(255),
	SECPASSWORD VARCHAR(255),
	USEREMAIL VARCHAR(255),
	PRIMARY KEY (LOGINID)
);

CREATE TABLE BOOKINVENTORY (
	INVENTORYID INT NOT NULL,
	BOOKID INT,
	BOOKSINSTOCK INT,
	PRIMARY KEY (INVENTORYID)
);

CREATE TABLE CREDITCARDINFO (
	CARDID INT NOT NULL,
	BUILDINGNO VARCHAR(10),
	CITY VARCHAR(50),
	COUNTRY VARCHAR(40),
	CREDITCARDTYPE VARCHAR(255),
	EXPIRATIONDATE VARCHAR(12),
	FIRSTNAME VARCHAR(30),
	LASTNAME VARCHAR(30),
	MIDDLENAME VARCHAR(30),
	PHONE VARCHAR(20),
	STATE VARCHAR(30),
	STREETNAME VARCHAR(50),
	STREETNO VARCHAR(10),
	ZIP VARCHAR(10),
	PRIMARY KEY (CARDID)
);

CREATE TABLE SHIPPINGTYPE (
	SHIPPINGID INT NOT NULL,
	RATE DOUBLE,
	TYPE VARCHAR(255),
	PRIMARY KEY (SHIPPINGID)
);

CREATE TABLE COUNTRYLIST (
	COUNTRYID INT NOT NULL,
	NAME VARCHAR(255),
	PRIMARY KEY (COUNTRYID)
);

CREATE TABLE RATINGS (
	RATINGSID INT NOT NULL,
	BOOKID INT,
	COMMENTS VARCHAR(3000),
	USERID INT,
	USERRATING5 INT,
	PRIMARY KEY (RATINGSID)
);

CREATE TABLE SHOPPINGCART (
	SCID INT NOT NULL,
	BOOKID INT,
	BOOKQUANTITY INT,
	USERID INT,
	PRIMARY KEY (SCID)
);

CREATE TABLE SEQUENCE (
	SEQ_NAME VARCHAR(50) NOT NULL,
	SEQ_COUNT DECIMAL(10 , 0),
	PRIMARY KEY (SEQ_NAME)
);

CREATE TABLE USERDETAILS (
	USERID INT NOT NULL,
	BUILDINGNO VARCHAR(10),
	CITY VARCHAR(50),
	COUNTRY VARCHAR(40),
	DATE VARCHAR(255),
	FIRSTNAME VARCHAR(30),
	LASTNAME VARCHAR(30),
	LOGINID INT,
	MIDDLENAME VARCHAR(30),
	PHONE VARCHAR(20),
	STATE VARCHAR(30),
	STREETNAME VARCHAR(50),
	STREETNO VARCHAR(10),
	ZIP VARCHAR(10),
	PRIMARY KEY (USERID)
);

CREATE INDEX FK_Tag_Books_BOOKID ON Tag (Books_BOOKID ASC);

CREATE UNIQUE INDEX USEREMAIL ON LOGIN (USEREMAIL ASC);

