--<ScriptOptions statementTerminator=";"/>

ALTER TABLE SEQUENCE DROP PRIMARY KEY;

DROP TABLE SEQUENCE;

CREATE TABLE SEQUENCE (
	SEQ_NAME VARCHAR(50) NOT NULL,
	SEQ_COUNT DECIMAL(10 , 0),
	PRIMARY KEY (SEQ_NAME)
);

